{{- $root := . }}
{{- $files := .Files.Glob "team-authorized-keys/*.pub" }}

{{- if (gt (len $files) 1) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hush-house.fullname" . }}-team-authorized-keys
  labels:
    app: {{ template "hush-house.name" . }}
    chart: {{ template "hush-house.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $path, $bytes := $files }}
{{- $name := (base $path) }}
{{- ($root.Files.Glob $path).AsConfig | nindent 2 }}
{{- end }}
{{- end }}
