---
platform: linux

image_resource:
  type: registry-image
  source: { repository: ubuntu, tag: bionic }

inputs:
- { name: hush-house }
- { name: helm-values, optional: true }

params:
  DEPLOYMENT:
  DEPLOYMENT_TYPE:

run:
  path: /bin/bash
  args:
  - -ce
  - |
    # install dependencies
    apt-get update && apt-get install -y make curl

    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    touch /etc/apt/sources.list.d/kubernetes.list
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install --no-install-recommends -y kubectl

    curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash


    # kubectl credential setup
    mkdir -p ~/.kube
    echo '((kube-config-b64))' | base64 -d >~/.kube/config


    # helm setup
    helm init --client-only
    echo '((helm-ca-cert-b64))' | base64 -d > $(helm home)/ca.pem
    echo '((helm-cert-b64))' | base64 -d > $(helm home)/cert.pem
    echo '((helm-key-b64))' | base64 -d > $(helm home)/key.pem

    helm repo remove local
    helm repo add concourse https://raw.githubusercontent.com/concourse/charts/gh-pages
    helm plugin install https://github.com/databus23/helm-diff --version master


    # conditionally set deployment credentials
    if [[ -d ./helm-values ]]; then
      cat ./helm-values/.values.yaml > ./hush-house/deployments/$DEPLOYMENT_TYPE/$DEPLOYMENT/.values.yaml
    fi


    # get into the deployment-type specific directory
    cd ./hush-house/deployments/$DEPLOYMENT_TYPE


    # conditionally perform the deployment if there are any diffs
    make diff-$DEPLOYMENT && \
      echo "No changes!" || \
      { [[ $? == "2" ]] && echo "y" | make deploy-$DEPLOYMENT; }

