# Default values for shuttle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

concourse:
  web:
    service:
      type: LoadBalancer
  worker:
    replicas: 3
    hardAntiAffinity: true
  postgresql:
    metrics:
      enabled: true
  concourse:
    web:
      externalUrl: http://hush-house.concourse-ci.org
      bindPort: 80
      kubernetes:
        keepNamespaces: false
      prometheus:
        enabled: true
    worker:
      baggageclaim:
        driver: overlay

prometheus:
  enabled: true
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
  server:
    persistentVolume:
      enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      label: grafana/datasource
    dashboards:
      enabled: true
      label: grafana/dashboard
