postgresql:
  enabled: false

concourse:
  image: concourse/concourse-rc
  imageTag: 6.0.0-rc.2

  secrets:
    teamAuthorizedKeys:
    - team: monitoring-hush-house
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDP5oT2CUJgRP55iNQD7NK4JzxRHSKstRXAV9EJw6O2Iaf9D9foHOaYNpgeIrRW4sbGvucLMhOBchp7yOhPTxn9jCUIGQttAWnFWW9SeHYOwPmbC30ggIIKmUQ/oWC6Xxou+KPotmqkKv+YyxNh8otTY5Sbz8VodEVqYR4hgXqunbSlcYJdMJqt6w0R319INdd898o6MbRrO5tj2I0ej8/Ct/n8Ijliawj3Mlm3g3w0O31C/Aj9jpEyvt+7JfcRWeJ1VcEnDsy4/UTqLh8P46LX/vzPQoPp54qrSaMcN7/1ylqn8XG5g+QWH4rmyJhH+0d1bt4v05M8b/UuHdXHgXVDMYyIFbvz2hRdhX7ZSHtP48e1B9t1S5Uo9gPG4D0jkWdMkpQf8/b4PXNF4nmBdKcWp9DqfYZOBMM17ZckOoWTnIORuZ/Xzgk1k11k0yAwRDxEksQuTSQexf5zxnku3ZediR5CwdbY9w4NiYB0DVCK7ktPi7Yg6RPrDgfALdB4vIg6jcWI3xw0ot2XVpZ2MGmUxL+ZlsymYncQ5p3pHRbznWbR2piniCa4rbE/KP0zFTDrNIMp2433nI0q5P1WbNuOQkL/XOIFkNr6f81ra9XJZWsV4Ytozivi5cg7hiPgCgxfUpnAQ+7NsSFYnV/gmmLjKUVCsdEwxqH5IxlxMYJqlQ=='

  postgresql:
    enabled: false

  web:
    annotations:
      rollingUpdate: "3"
    replicas: 2
    env:
    - name: CONCOURSE_X_FRAME_OPTIONS
      value: ""
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: ci-web
                release: ci
    service:
      type: LoadBalancer
      loadBalancerIP: 34.69.51.78
    resources:
      requests:
        cpu: 1500m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 1Gi

  persistence:
    worker:
      storageClass: ssd
      size: 750Gi

  worker:
    replicas: 8
    annotations:
      manual-update-revision: "1"
    terminationGracePeriodSeconds: 3600
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 10
      timeoutSeconds: 45
    nodeSelector: { cloud.google.com/gke-nodepool: ci-workers }
    hardAntiAffinity: true
    env:
    - name: CONCOURSE_GARDEN_NETWORK_POOL
      value: "10.254.0.0/16"
    - name: CONCOURSE_GARDEN_MAX_CONTAINERS
      value: "500"
    - name: CONCOURSE_GARDEN_DENY_NETWORK
      value: "169.254.169.254/32"
    resources:
      limits:   { cpu: 7500m, memory: 14Gi }
      requests: { cpu: 0m,    memory: 0Gi  }

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      clusterName: ci
      containerPlacementStrategy: limit-active-tasks
      maxActiveTasksPerWorker: 5
      enableGlobalResources: true
      encryption: { enabled: true }
      externalUrl: https://ci.concourse-ci.org
      kubernetes:
        keepNamespaces: false
        enabled: false
        createTeamNamespaces: false
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      vault:
        enabled: true
        url: https://vault.vault.svc.cluster.local:8200
        sharedPath: shared
        authBackend: "cert"
        useCaCert: true
      tls: { enabled: true, bindPort: 443 }
      postgres:
        host: 34.69.204.254
        database: atc
        sslmode: verify-ca

    worker:
      rebalanceInterval: 2h
      baggageclaim: { driver: overlay }
      healthcheckTimeout: 40s
