# Configuration for serving the metrics dashboards
# with TLS enabled.
tls:
  enabled: true
  ## Certificate
  # cert:
  ## Private key
  # key:


# Configuration for the prometheus dependency.
prometheus:
  enabled: true
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
    affinity:
      nodeAffinity: &affinityToNonEphemeral
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist

  server:
    persistentVolume:
      enabled: true
      size: 30Gi
      storageClass: ssd
    affinity:
      nodeAffinity: *affinityToNonEphemeral


# Configuration for the Grafana dependency.
grafana:
  enabled: true
  livenessProbe:
    httpGet:
      scheme: HTTPS
  readinessProbe:
    httpGet:
      scheme: HTTPS
  extraSecretMounts:
  - name: metrics-tls
    mountPath: /tls
    secretName: metrics-tls
    readOnly: true
  grafana.ini:
    server:
      protocol: https
      domain: metrics-hush-house.concourse-ci.org
      root_url: https://metrics-hush-house.concourse-ci.org
      cert_file: /tls/cert
      cert_key: /tls/key
    users:
      auto_assign_organization_role: Editor
    auth.anonymous:
      enabled: true
  service:
    loadBalancerIP: 35.202.234.135
    port: 443
    type: LoadBalancer
  sidecar:
    datasources:
      enabled: true
      label: grafana/datasource
    dashboards:
      enabled: true
      label: grafana/dashboard
