postgresql:
  enabled: false

concourse:
  image: concourse/concourse
  imageDigest: sha256:38cb311fac63c09dee250c888c7488b1aba964404bdcc268e02ad916af509bc9

  postgresql:
    enabled: false

  persistence:
    worker:
      storageClass: ssd
      size: 1000Gi

  web:
    enabled: false

  worker:
    annotations:
      rollingUpdate: "2"
    replicas: 5
    terminationGracePeriodSeconds: 3600
    livenessProbe:
      periodSeconds: 60
      timeoutSeconds: 30
    nodeSelector: { cloud.google.com/gke-nodepool: workers-1 }
    hardAntiAffinity: true
    env:
    - name: CONCOURSE_GARDEN_NETWORK_POOL
      value: "10.254.0.0/16"
    - name: CONCOURSE_GARDEN_MAX_CONTAINERS
      value: "500"
    - name: CONCOURSE_GARDEN_DENY_NETWORK
      value: "169.254.169.254/32"
    resources:
      limits:
        cpu: 15000m
        memory: 29Gi
      requests:
        cpu: 10000m
        memory: 25Gi

  concourse:
    worker:
      ephemeral: false
      rebalanceInterval: 1h
      baggageclaim: { driver: detect }
      healthcheckTimeout: 25s
      tsa:
        hosts: ['hush-house-web.hush-house.svc.cluster.local:2222']

  secrets:
    hostKeyPub: |-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMU5L98yRnMsQosvfeeC/5qEUy9P13RdO88FLRYTNZIDX7GVW4NRcVqEcysNckoGYPVPeX19I03EXeO4yf71in4F4u9JV+SZaefyeG/6Q9fAO5HbdTdooRPm9yaydDHSwVKx1yPkhm/HIqNvwSBbqipLhjq3zPKCXKDMKYWoPQf/OeERHmW9sTbfbvB1mgKVUGtU8Eox787k8FG/Gq17iHPwxQd8tzsaa/zgUTbjHuOMhSrm8hgL0GYPn8OaS+2Y/FfCiLZWZVeTmLv11F26r1G8I7SSs5+qfn5ZUz3ZfjRcuv077VkeyCVGtxKcjSubMe6HfmmSx0TkwcKjA4vqWh pivotal@DX187.local
